# -*- coding: utf-8 -*-
"""calculadorabásica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171oRwiD_LpT2oVniVbGvANIKoVmjJwEP

Projeto dedicado ao uso de recursos básicos em uma calculadora

Linguagem utilizada: Python

## Testando o IF
"""

print("-------Calculadora Simples-------")

numero1 = int(input("Digite um número: "))
numero2 = int(input("Digite outro número: "))

operacao = int(input("Digite a operação desejada: (1-Soma|2-Subtração|3-Multiplicação|4-Divisão) "))

if (operacao == 1):
    print("A soma dos números é: " + str(numero1 + numero2))
elif(operacao == 2):
    print("A subtração dos números é: " + str(numero1 - numero2))
elif (operacao == 3):
    print("A multiplicação dos números é: " + str(numero1 * numero2))
elif (operacao == 4):
    if (numero2 == 0):
        print("Não é possível dividir por zero")
    else:
        print("A divisão dos números é: " + str(numero1 / numero2))
else:
    print("Operação inválida")

"""## Testando o While
Enquanto o usuário digita o número 1, o código continuar aparecendo para que seja feito um novo calculo.
"""

print("-------Calculadora Simples-------")

calcular = int(input("Deseja realizar uma operação matemática? (1- Sim/2- Não)"))

while calcular == 1:

  numero1 = int(input("Digite um número: "))
  numero2 = int(input("Digite outro número: "))

  operacao = int(input("Digite a operação desejada: (1-Soma|2-Subtração|3-Multiplicação|4-Divisão) "))

  if (operacao == 1):
      print("A soma dos números é: " + str(numero1 + numero2))
  elif(operacao == 2):
      print("A subtração dos números é: " + str(numero1 - numero2))
  elif (operacao == 3):
      print("A multiplicação dos números é: " + str(numero1 * numero2))
  elif (operacao == 4):
      if (numero2 == 0):
          print("Não é possível dividir por zero")
      else:
          print("A divisão dos números é: " + str(numero1 / numero2))
  else:
      print("Operação inválida")

  calcular = int(input("Deseja realizar uma operação matemática? (Sim/Não)"))

print("Obrigado por utilizar a calculadora!")

"""## UTLIZANDO FUNÇÃO"""

def exibir_operacoes():
  print("\n ----- Calculadora -----")
  print("1- Soma")
  print("2- Subtração")
  print("3- Multiplicação")
  print("4- Divisão")
  print("5- Sair")

def obter_numero(mensagem):
  while True:
      return float(input(mensagem))

def definir_operacao(operacao, numero1, numero2):
  if (operacao == 1):
    return numero1 + numero2
  elif(operacao == 2):
    return numero1 - numero2
  elif (operacao == 3):
    return numero1 * numero2
  elif (operacao == 4):
    if (numero2 == 0):
      print("Não é possível dividir por zero")
    else:
      return numero1 / numero2
  else:
    print("Operação inválida")

while True:
  exibir_operacoes()
  operacao = int(input("Digite a operação desejada: "))

  if operacao == 5:
    print("Obrigada por utilizar nossa calculadora!")
    break

  numero1 = obter_numero("Digite o primeiro número: ")
  numero2 = obter_numero("Digite o segundo número: ")

  resultado = definir_operacao(operacao, numero1, numero2)
  print("Resultado: ", resultado)