# -*- coding: utf-8 -*-
"""Projeto-Patitas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_8j1WRpX3dzY-qn9JmAQM809VGjORiO
"""

import os

# --- Constants for menu options ---
OPCAO_CADASTRAR_ANIMAL = 1
OPCAO_CADASTRAR_ONG = 2
OPCAO_EXIBIR_ANIMAIS = 3
OPCAO_CADASTRAR_USUARIO = 4
OPCAO_SAIR = 5

animais_cadastrados = [
    {'especie': 'Cachorro', 'nome': 'Rex', 'idade': '3', 'descricao': 'Cachorro brincalhão'},
    {'especie': 'Gato', 'nome': 'Miau', 'idade': '2', 'descricao': 'Gato carinhoso'},
]

def cadastrar_animal():
  """
  Solicita informações ao usuário para cadastrar um novo animal
  e o adiciona à lista global `animais_cadastrados`.
  """
  especie = input('Digite a espécie do animal: ')
  nome_animal = input('Digite o nome do animal: ')
  idade_animal = input('Digite a idade do animal: ')
  descricao_animal = input('Digite a descrição: ')
  novo_animal = {'especie': especie, 'nome': nome_animal, 'idade': idade_animal, 'descricao': descricao_animal}
  animais_cadastrados.append(novo_animal)
  print('Animal cadastrado com sucesso!')

def exibir_menu():
  """
  Exibe o menu principal do sistema 'Patitas' e gerencia as opções do usuário.
  """
  while True: # Loop para manter o menu ativo
    print('\n--- Patitas ---')
    print(f'{OPCAO_CADASTRAR_ANIMAL}- Cadastrar novo animal')
    print(f'{OPCAO_CADASTRAR_ONG}- Cadastrar nova ONG')
    print(f'{OPCAO_EXIBIR_ANIMAIS}- Exibir animais cadastrados')
    print(f'{OPCAO_CADASTRAR_USUARIO}- Cadastrar usuários')
    print(f'{OPCAO_SAIR}- Sair')

    try:
        escolha_usuario = int(input('Escolha uma opção abaixo: '))
    except ValueError:
        print('Opção inválida! Por favor, digite um número.')
        continue # Voltar ao início do loop

    if escolha_usuario == OPCAO_CADASTRAR_ANIMAL:
          cadastrar_animal()
    elif escolha_usuario == OPCAO_CADASTRAR_ONG:
          nome_ong = input('Digite o nome da ONG: ')
          numero_animais = input('Digite o numero de animais: ')
          endereco_ong = input('Digite o endereco: ')
          print(f'ONG {nome_ong} cadastrada (dados não persistidos).') # Apenas para feedback
    elif escolha_usuario == OPCAO_EXIBIR_ANIMAIS:
          if not animais_cadastrados:
                print('Nenhum animal cadastrado ainda.')
          else:
                print('Animais Cadastrados:')
                for animal in animais_cadastrados:
                      print(f"Espécie: {animal['especie']}, Nome: {animal['nome']}, Idade: {animal['idade']}, Descrição: {animal['descricao']}")
    elif escolha_usuario == OPCAO_CADASTRAR_USUARIO:
      print('Cadastro de usuários: ')
      nome_usuario = input('Digite seu nome: ')
      email_usuario = input('Digite seu email: ')
      print(f'Usuário {nome_usuario} cadastrado.') # Apenas para feedback
    elif escolha_usuario == OPCAO_SAIR:
      print('Obrigada por usar o sistema! Até mais!')
      break # Sai do loop
    else:
      print('Opção inválida! Por favor, escolha uma opção entre 1 e 5.')

def main():
  """
  Função principal para iniciar o sistema 'Patitas'.
  """
  exibir_menu()

# --- Ponto de entrada do programa ---
if __name__ == '__main__':
  main()